# Generated by Django 5.2.1 on 2025-05-25 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix Unitaire')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('alert_quantite', models.PositiveIntegerField(help_text='Seuil pour la notification de stock faible.', verbose_name='Alert Quantité')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.produit')),
            ],
        ),
    ]
