# Generated by Django 5.2.1 on 2025-05-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a product image', null=True, upload_to='products/', verbose_name='Product Image'),
        ),
    ]
