# Generated by Django 5.2.1 on 2025-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products/', verbose_name='Product Image'),
        ),
    ]
